version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "plugin-services-stage"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xii49d10mx49"
s3_prefix = "plugin-services-stage"
region = "us-east-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "zoomApiName=\"zoomStage\""
image_repositories = []
