---
name: Deploy lambda functions to dev/prod

on: 
  push:
    branches:
      - develop
      - master
      
  workflow_dispatch:
  
  
jobs:
  pre-deploy: 
    runs-on: ubuntu-latest
    env: 
      BRANCH: ${{ github.ref_name }}
    outputs:
      env-name: ${{ steps.info.outputs.env-name }}
      sam-config: ${{ steps.info.outputs.sam-config }}
    steps: 
      - name: Get info
        id: info
        shell: bash
        run: |
          if [ "${BRANCH}" == "master" ]; then
             ENV=production
             SAM_CONFIG=samconfig.prod.toml
          fi
          echo "env-name=${ENV:-development}" >> "$GITHUB_OUTPUT"
          echo "sam-config=${SAM_CONFIG:-samconfig.dev.toml}" >> "$GITHUB_OUTPUT"
          
  deploy:
    runs-on: ubuntu-latest
    needs: pre-deploy
    environment: 
      name: ${{ needs.pre-deploy.outputs.env-name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
      - uses: aws-actions/setup-sam@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        run: sam build
      - name: Deploy
        run: |
           sam deploy --config-file ${{ needs.pre-deploy.outputs.sam-config }}
