---
name: Deploy lambda functions to production

on: 
  push:
    branches:
      - master
      
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
      - uses: aws-actions/setup-sam@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        run: sam build
      - name: Deploy
        run: sam deploy --config-file samconfig.toml
